[tool.poetry]
name = "tap-pipedream"
version = "0.0.0"
description = "`tap-pipedream` is a Singer tap for Pipedream, built with the Meltano SDK for Singer Taps."
license = "Apache-2.0"
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
maintainers = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-pipedream"
repository = "https://github.com/edgarrmondragon/tap-pipedream"
documentation = "https://github.com/edgarrmondragon/tap-pipedream#readme"
keywords = [
  "ELT",
  "singer.io",
  "Pipedream",
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
singer-sdk = "~=0.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "~=7.4"

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]

[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = [
  "poetry-core>=1",
  "poetry-dynamic-versioning",
]

[tool.poetry.scripts]
# CLI declaration
"tap-pipedream" = "tap_pipedream.tap:TapPipedream.cli"

[tool.poetry-dynamic-versioning]
enable = true
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=[commit]) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance, metadata=[commit]) }}
    {%- endif -%}
"""
metadata = true
style = "pep440"
vcs = "git"

[tool.ruff]
line-length = 88
src = ["tap_pipedream", "tests"]
target-version = "py38"

[tool.ruff.lint]
ignore = [
  "ANN101", # missing-type-self
  "DJ", # flake8-django
  "COM812",  # missing-trailing-comma
  "ISC001",  # single-line-implicit-string-concatenation
]
select = ["ALL"]
unfixable = [
  "ERA001",  # commented-out-code
]

[tool.ruff.lint.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101", # assert
  "SLF001", # private-member-access
]

[tool.ruff.lint.isort]
known-first-party = ["tap_pipedream"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
convention = "google"
